[package]
name = "eoproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.12", features = ["toml", "ron"] }
chrono = "0.4"
lazy_static = "1.0"
log = "0.4"
num-traits = "0.2"
pretty_env_logger = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["full", "tracing"] }
serde_derive = "^1.0.8"
serde = "^1.0.8"
console-subscriber = { version = "0.1", optional = true }
eo = { git = "https://github.com/sorokya/eo", features = ["use_serde"] }
